### ISSUE TITLE
parallelMap on AWS

### ISSUE THREAD

**Issue by rpinsler** [berndbischl/parallelMap#35]
Hi all,

how easy is it to use parallelMap (in combination with mlr) on AWS? If I understand correctly, BatchJobs mode would be preferable to MPI due to job scheduling, etc. Therefore, you need a job scheduler like TORQUE, LSF or SLURM. In addition, openMPI with Rmpi is still needed, right?

According to [this paper](http://www.jstatsoft.org/v64/i11/paper), a suitable AMI and a globally shared FS are necessary, too. Do you know of any AMI that comes close to this setup? How can you ensure a globally shared FS on AWS? To me it sounds like this is [yet to come](https://aws.amazon.com/de/blogs/aws/amazon-elastic-file-system-shared-file-storage-for-amazon-ec2/).

Best regards,
Robert

**Comment by berndbischl** [comment]
> how easy is it to use parallelMap (in combination with mlr) on AWS?

I dont know because I have not tried so far. I have used parallelMap / BatchJobs on Microsoft Azure, which may or may not be similar. I used the SSH mode for BatchJobs, because 
a) we had multiple machines b) I did not want to install stuff like SLURM for this and all machines belonged exclusively to us.
Of course, there was no shared fs :( 
So I used sshfs. I was pretty sure that this was going to turn out to be a bad idea, because of lagging and potential instability. But it worked smoothly without problems to my surprise. 
I am also quite sure that for this to work the number of jobs should not be too large. But one can always use chunking for this, and the other newer options we have in BatchJobs to reduce problems with the fs.

Does this help? 

So my clonclusion is: Depending on what you want to do, and how AWS works, this MIGHT not to be too hard, for not so complicated tasks.

**Comment by rpinsler** [comment]
What's the advantage of using BatchJobs instead of plain MPI when you don't have a job scheduler like SLURM, then?

**Comment by berndbischl** [comment]
I dont get your question. I mean, it was you who asked whether BJ would run on such a system. I tried to answer your question as good as I can.

2nd, as for as I know, resources on such systems are not contested . So installing something like SLURM does not seem to make sense to me. What you by, you can use, without other people interferring. (NB: I dont know whether this is correct, and BJ was designed to work on other systems, like HPC clusters. Still, it was you who asked abou this).

3rd: My reason why I used this on Azure was this:

- I had a complex experiment of long runnig jobs
- I wanted to use BatchExperiments
- Due to the complexity, job errors were likely
- it was also likely that I would want to extend the experiment by later adding jobs (happened indeed)
- due to all of this reasons I really wanted the DB in background that BE offered

**Comment by rpinsler** [comment]
Thanks for your answer. The reason why I ask is because I am still unsure whether to use MPI or BatchJobs to use parallelMap + mlr on a larger scale. What I get from you is that it depends on the requirements. Using BatchJobs seems a bit more complicated but is preferable the larger and more complex the experiments become, right?

**Comment by berndbischl** [comment]
First of all: Yes these types of questions are notoriously hard to answer. Because I don't know exactly what you want to do. And also in my own experiments I use different approaches, depending on what I want to do. Actually this is we tried to make stuff like BatchJobs and parallelMap flexible and configurable. So we can change approaches when a project demands it. 

My usual decision process might work like this:

a) one machine, more a less a map operation, where jobs are "very similar in structure" and dont run too long (basically some thing where parallel computing makes it an interactive operation): multicore / multicore mode in parallelmap

b) a few machine, more a less a map operation, where jobs are "very similar in structure" and dont run too long (basically some thing where parallel computing makes it an interactive operation): mpi / mpi mode in parallelmap

c) a very complex experiments where jobs usually use different experimental settings / packages. 
thats my usual case. then i use BE.

**Comment by berndbischl** [comment]
To be honest, I think we should set up a web page to document such examples to help people decide. 
with pros and cons of different approaches. 
but thats a lot of work :)

still i think this is kinda necessary and a service to many people.
